apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ replace "." "-" .Values.domain }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    site: {{ .Values.domain }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      site: {{ .Values.domain }}
  template:
    metadata:
      labels:
        site: {{ .Values.domain }}
    spec:
      containers:
      - name: {{ replace "." "-" .Values.domain }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsNonRoot: {{ .Values.nonRootUser}}
        ports:
        - containerPort: {{ .Values.containerPort }}
