apiVersion: v1
kind: Service
metadata:
  name: {{ replace "." "-" .Values.domain}}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    site: {{ .Values.domain}}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
