name: Sync Helm Repo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          path: 'main'
      - uses: actions/checkout@v2
        with:
          ref: 'repo'
          path: 'repo'
      - uses: azure/setup-helm@v1
      - name: Sync Helm Repo
        run: cd main && sh sync.sh
      - name: Move repo folder
        run: |
          mv main/repo/* repo/
          cd repo
          git config user.email "donnie@thedadams.com"
          git config user.name "Donnie Adams"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repo" -m "${{ github.event.head_commit.message }}"
          git push
